branches:
  only:
  - "/^v[0-9]/"
language: node_js
node_js:
- '6'
addons:
  code_climate:
    repo_token: a161a57cbff98f0d2f677d076f901a042c73992bcf3465b7820d5c0ea3aea295
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: aCKjuXjJpyGSkOTsXYm/hDeUB6hQ4oABEllb0GL0LVmovjH/1KTKwipvUf756XSQ9gyQdozCnHV2BIFrSZurxLQFBIYLCmn2WSlVC2AxR3BIFNTjWCvzIsMoOf/xfU/esokmDrdzb7AdSxD/MlCmw01V+dql3tvGyo/nAR/fj1tMubO5f0HkMEuL2/DTxPRvnGxuEXzY6hYzHCyC2CElO3pP8X1DAj1CM+5V53cnhKlVRQ6qdGpEj95l27ny6Txao1LIoiwDEedpgfrn3iUgDNy4uh7BGpGsFPm/33eMBtg+VlAEwto1FhEJ51pXRD7tY7FlFwb9hM8c9fcDgGEBDhkc/aF/hbk0sa/AcLqydVYoCvTDDx6RsdmMwMyXJW73oB+B8zotpxkz49DuAq/FeqmeTr1dekVDDN9QYCckMsa7K/VKWH6VScgVFMTvOYHr9w0jOb5P0ZbjLaIVoNtPTcbM37If+1UwCCn0dt6krkfGk5eqok/2C9iMKE6N9Gyr5AOb7Mx/gxrsAKKG+LI3GT01/OwTwYoyeQNcUuSMDjQaaKfCdZiOqcqZf2CzCEcvMCQHW1XQR1DkiXUXdgeVGT8bUFW2nwuJFP3J0Jvlz7SObW6NBKkE9kT3tcCjKYhIzLSWQFcW/DMhvhRAXju8aGowyJqlMOjNc8nZlUSVWcg=
  on:
    tags: true
    branches: true
